import {test} from 'node:test';import assert from 'node:assert/strict';import ExcelJS from 'exceljs';
import {reference,cadPrices,emptyPortfolio,setHolding,trade,total,holdingValues,simulate,scenarioRates,annualFee,parsePriceFile,type Snapshot} from '../lib/lab';import {createWorkbook} from '../lib/export';
const prices=cadPrices(reference);let portfolio=emptyPortfolio(100000);[100,100,0,200,200,200,100].forEach((d,i)=>{if(d)portfolio=setHolding(portfolio,i,d/prices[i],prices)});
const snapshot:Snapshot={budget:100000,portfolio,prices:reference,account:'TFSA',goal:'University or college',horizon:'In 2–5 years',risk:'Some ups and downs'};
test('source snapshot, USD conversion and amount/share equivalence',()=>{assert.equal(prices[0],330.32*1.4243);assert.equal(prices[3],212.1);assert.equal(reference.prices[0].date,'2026-10-01');const p=setHolding(emptyPortfolio(100000),0,100/prices[0],prices);assert.equal(holdingValues(p,prices)[0],10000);assert.equal(p.cash,90000);assert.equal(total(p,prices),100000);const oneShare=setHolding(emptyPortfolio(100000),0,1,prices);assert.equal(holdingValues(oneShare,prices)[0],Math.round(prices[0]*100));assert.equal(total(oneShare,prices),100000)});
test('cash counted once, purchases bounded, changing one field replaces rather than duplicates',()=>{assert.equal(portfolio.cash,10000);assert.equal(total(portfolio,prices),100000);const replacement=setHolding(portfolio,0,50/prices[0],prices);assert.equal(replacement.cash,15000);assert.equal(total(replacement,prices),100000);assert.throws(()=>setHolding(portfolio,0,1000/prices[0],prices));assert.throws(()=>setHolding(portfolio,0,-1,prices));assert.throws(()=>setHolding(portfolio,0,NaN,prices));assert.throws(()=>setHolding(portfolio,0,1e-12,prices));assert.equal(total(emptyPortfolio(0),prices),0)});
test('four fictional events, cash/FX/shares unchanged, account independent',()=>{const outcomes=[['company',98000],['decline',82500],['recovery',114000],['mixed',93500]] as const;outcomes.forEach(([id,value])=>{const r=simulate(portfolio,prices,scenarioRates(id,0));assert.equal(r.total,value);assert.equal(r.change,value-100000);assert.equal(portfolio.cash,10000);assert.equal(portfolio.shares[0],100/prices[0]);});assert.equal(simulate(emptyPortfolio(100000),prices,scenarioRates('decline',0)).total,100000);assert.throws(()=>scenarioRates('company',4));assert.throws(()=>scenarioRates('unknown',0));assert.deepEqual(simulate(snapshot.portfolio,prices,scenarioRates('decline',0)),simulate({...snapshot,account:'RRSP'}.portfolio,prices,scenarioRates('decline',0)))});
test('post-event sales and buys conserve value, disallow over-sale and over-spend',()=>{const event=simulate(portfolio,prices,scenarioRates('decline',0));let revised={shares:[...portfolio.shares],cash:portfolio.cash};revised=trade(revised,0,revised.shares[0],'sell',event.prices);assert.equal(revised.cash,17500);assert.equal(revised.shares[0],0);revised=trade(revised,4,100/event.prices[4],'buy',event.prices);assert.equal(revised.cash,7500);assert.equal(total(revised,event.prices),82500);assert.throws(()=>trade(revised,0,1,'sell',event.prices));assert.throws(()=>trade(revised,0,1000/event.prices[0],'buy',event.prices));assert.throws(()=>trade(revised,0,0,'buy',event.prices))});
test('fees: sourced MER estimates rounded per ETF, not charged for instant events',()=>{assert.equal(annualFee(portfolio,prices),52);const event=simulate(portfolio,prices,scenarioRates('decline',0));assert.equal(annualFee(portfolio,event.prices),44);assert.equal(event.total,82500)});
test('import validation: exact tickers, currencies, dates, positive values and safe sources',()=>{const parsed=parsePriceFile(reference);assert.equal(parsed.verified,false);assert.deepEqual(cadPrices(parsed),prices);const modify=(fn:(p:any)=>void)=>{const p=JSON.parse(JSON.stringify(reference));fn(p);return p};assert.throws(()=>parsePriceFile(modify(p=>p.prices[0].close=0)));assert.throws(()=>parsePriceFile(modify(p=>p.prices[0].currency='CAD')));assert.throws(()=>parsePriceFile(modify(p=>p.prices[0].source='javascript:alert(1)')));assert.throws(()=>parsePriceFile(modify(p=>p.prices[0].date='2026-02-31')));assert.throws(()=>parsePriceFile(modify(p=>p.fx.rate=-1)));assert.throws(()=>parsePriceFile(modify(p=>p.prices[1].ticker='AAPL')));assert.throws(()=>parsePriceFile({}));});
test('Excel reopens with matching quantities, prices, FX, formulas, accounts, outcomes and reflection',async()=>{const event={id:'decline',target:0,rates:scenarioRates('decline',0)},post=simulate(portfolio,prices,event.rates);let revised=trade(portfolio,0,portfolio.shares[0],'sell',post.prices);revised=trade(revised,4,100/post.prices[4],'buy',post.prices);const wb=await createWorkbook({original:snapshot,revised,event,reflection:'I kept less money in one company.'});const buffer=await wb.xlsx.writeBuffer(),reopened=new ExcelJS.Workbook();await reopened.xlsx.load(buffer);assert.equal(reopened.worksheets.length,6);const value=(sheet:string,cell:string)=>reopened.getWorksheet(sheet)!.getCell(cell).value as {formula:string,result:number};assert.equal(value('Original portfolio','E10').result,1000);assert.equal(value('Original portfolio','E9').result,100);assert.equal(value('Scenario results','G10').result,825);assert.equal(value('Scenario results','H10').result,-175);assert.equal(value('Revised portfolio','E10').result,825);assert.equal(value('Revised portfolio','E9').result,75);assert.equal(reopened.getWorksheet('Original portfolio')!.getCell('C2').value,portfolio.shares[0]);assert.equal(reopened.getWorksheet('Revised portfolio')!.getCell('C2').value,0);assert.equal(reopened.getWorksheet('Reference prices')!.getCell('C2').value,330.32);assert.equal(value('Reference prices','D2').result,prices[0]);assert.equal(reopened.getWorksheet('Reference prices')!.getCell('L1').value,1.4243);assert.equal(reopened.getWorksheet('Reference prices')!.getCell('E2').value,'2026-10-01');assert.equal(reopened.getWorksheet('Reference prices')!.getCell('F2').value,reference.prices[0].source);assert.equal(reopened.getWorksheet('Workshop')!.getCell('B5').value,'TFSA');assert.equal(reopened.getWorksheet('Workshop')!.getCell('B19').value,'I kept less money in one company.');assert.match(value('Revised portfolio','E9').formula,/Scenario results/)});
test('Excel supports all-cash zero budgets and literal reflection; rejects unreconciled revised cash',async()=>{const zero={...snapshot,budget:0,portfolio:emptyPortfolio(0)};const wb=await createWorkbook({original:zero,revised:zero.portfolio,event:null,reflection:'=HYPERLINK("test")'});assert.equal(typeof wb.getWorksheet('Workshop')!.getCell('B19').value,'string');assert.equal(wb.getWorksheet('Original portfolio')!.getCell('F10').result,0);await assert.rejects(()=>createWorkbook({original:snapshot,revised:{...portfolio,cash:0},event:null,reflection:''}));});

import {assets,allocation,allocate,priceFor,snapshotFX} from '../lib/builder';
import {createBuilderWorkbook} from '../lib/builder-export';
test('Builder counts cash once and rejects over-allocation',()=>{let amounts=assets.map(()=>0);amounts=allocate(100000,amounts,0,50000);amounts=allocate(100000,amounts,4,25000);amounts=allocate(100000,amounts,7,15000);amounts=allocate(100000,amounts,11,5000);const m=allocation(100000,amounts);assert.equal(m.cash,5000);assert.equal(m.byGroup.reduce((s,g)=>s+g.value,0),100000);assert.equal(m.fee,15);assert.throws(()=>allocate(100000,amounts,1,5001));amounts=allocate(100000,amounts,0,0);assert.equal(allocation(100000,amounts).cash,55000);assert.throws(()=>allocation(50000,amounts.map(()=>10000)));assert.throws(()=>allocate(100000,amounts,0,-1));});
test('Builder workbook round trip matches all allocations and references',async()=>{const amounts=assets.map((_,i)=>i===0?50000:i===4?25000:i===7?15000:i===11?5000:0);const wb=await createBuilderWorkbook({budget:100000,amounts,account:'Non-registered',goal:'University'});const buffer=await wb.xlsx.writeBuffer();const loaded=new ExcelJS.Workbook();await loaded.xlsx.load(buffer);const p=loaded.getWorksheet('Portfolio')!;assert.equal(p.getCell('D2').value,500);assert.equal((p.getCell(`D${assets.length+2}`).value as any).result,50);assert.equal((p.getCell(`D${assets.length+3}`).value as any).result,1000);assert.equal((p.getCell('E2').value as any).result,.5);assert.equal((loaded.getWorksheet('Asset distribution')!.getCell('B4').value as any).result,150);assert.equal(loaded.getWorksheet('References')!.getCell('E2').value,priceFor(assets[0])!.date);assert.equal(loaded.getWorksheet('Portfolio settings')!.getCell('B4').value,'Non-registered');});

import {accountDistribution} from '../lib/builder';
import {parseYahoo} from '../lib/market';
test('Account balances reconcile, cash belongs to one account, and moving accounts preserves asset mix',()=>{const amounts=assets.map(()=>0),assigned=assets.map(()=>'Non-registered' as const) as import('../lib/lab').Account[];amounts[0]=40000;amounts[4]=30000;amounts[11]=10000;assigned[0]='TFSA';assigned[4]='FHSA';assigned[11]='RRSP';const distribution=accountDistribution(100000,amounts,assigned,'Non-registered');assert.equal(distribution.reduce((s,a)=>s+a.value,0),100000);assert.equal(distribution.find(a=>a.account==='Non-registered')!.cash,20000);assert.equal(distribution.find(a=>a.account==='RRSP')!.crypto,10000);const before=allocation(100000,amounts);assigned[0]='FHSA';assert.deepEqual(allocation(100000,amounts),before);assert.equal(accountDistribution(100000,amounts,assigned,'Non-registered').find(a=>a.account==='FHSA')!.value,70000);assert.throws(()=>accountDistribution(100000,amounts,[], 'TFSA'));});
test('Yahoo parsing preserves source timestamp and rejects invalid or mismatched prices',()=>{const input={chart:{result:[{meta:{symbol:'AAPL',currency:'USD',regularMarketPrice:333.69,regularMarketTime:1790971201}}]}};const q=parseYahoo(input,'AAPL');assert.equal(q.price,333.69);assert.equal(q.asOf,'2026-10-02T20:00:01.000Z');assert.equal(q.currency,'USD');assert.throws(()=>parseYahoo(input,'MSFT'));assert.throws(()=>parseYahoo({chart:{result:[{meta:{symbol:'AAPL',currency:'USD',regularMarketPrice:NaN}}]}},'AAPL'));});
test('Account Excel export preserves holding accounts, live references and FX',async()=>{const amounts=assets.map(()=>0);amounts[0]=50000;const assigned=assets.map(()=>'Non-registered' as const) as import('../lib/lab').Account[];assigned[0]='FHSA';const q=parseYahoo({chart:{result:[{meta:{symbol:'AAPL',currency:'USD',regularMarketPrice:333.69,regularMarketTime:1790971201}}]}},'AAPL');const wb=await createBuilderWorkbook({budget:100000,amounts,assigned,account:'TFSA',goal:'Home',market:{quotes:{AAPL:q},fx:{rate:1.42,date:q.asOf,source:'https://finance.yahoo.com/quote/CAD%3DX/'},errors:[],fetchedAt:q.asOf}});const buffer=await wb.xlsx.writeBuffer();const loaded=new ExcelJS.Workbook();await loaded.xlsx.load(buffer);assert.equal(loaded.getWorksheet('Portfolio')!.getCell('I2').value,'FHSA');assert.equal(loaded.getWorksheet('References')!.getCell('D2').value,333.69);assert.equal(loaded.getWorksheet('Portfolio settings')!.getCell('B9').value,1.42);const sheet=loaded.getWorksheet('Account distribution')!;assert.equal((sheet.getCell('B2').value as any).result,500);assert.equal((sheet.getCell('B4').value as any).result,500);assert.match((sheet.getCell('B4').value as any).formula,/SUMIF/);});

test('Every instrument has a positive dated price; tradable instruments use sourced Yahoo snapshots',()=>{for(const a of assets){const p=priceFor(a);assert.ok(p.close>0);assert.ok(p.date);if(a.symbol){assert.match(p.source,/^https:\/\/finance.yahoo.com\/quote\//);assert.equal(p.kind,'Dated Yahoo price snapshot')}else{assert.equal(p.close,100);assert.equal(p.currency,'CAD');assert.equal(p.kind,'Illustrative practice price')}}assert.ok(snapshotFX.rate>0)});
test('Snapshot prices, FX, and units agree with Excel for all instruments',async()=>{const amounts=assets.map(()=>100);const budget=100000,wb=await createBuilderWorkbook({budget,amounts,account:'Non-registered',goal:'Explore'});const loaded=new ExcelJS.Workbook();await loaded.xlsx.load(await wb.xlsx.writeBuffer());assert.equal(loaded.getWorksheet('Portfolio settings')!.getCell('B9').value,snapshotFX.rate);for(const [i,a] of assets.entries()){const p=priceFor(a),cad=p.close*(p.currency==='USD'?snapshotFX.rate:1),row=i+2;assert.equal(loaded.getWorksheet('References')!.getCell(`F${row}`).value,cad);assert.equal((loaded.getWorksheet('Portfolio')!.getCell(`F${row}`).value as any).result,1/cad)}assert.equal((loaded.getWorksheet('Portfolio')!.getCell(`D${assets.length+2}`).value as any).result,1000-assets.length)});
