import ExcelJS from 'exceljs';
import {assets,groups,allocation,priceFor,accountDistribution,accountTypes,snapshotFX,type BuilderState} from './builder';
import {reference,accounts,type Account} from './lab';
export async function createBuilderWorkbook(data:BuilderState){
 const assigned=data.assigned??assets.map(()=>data.account as Account),byAccount=accountDistribution(data.budget,data.amounts,assigned,data.account as Account),fx=data.market?.fx??snapshotFX;
 const mix=allocation(data.budget,data.amounts),wb=new ExcelJS.Workbook();wb.creator='Teen Finance Club';wb.calcProperties.fullCalcOnLoad=true;
 const info=wb.addWorksheet('Portfolio settings');info.columns=[{width:30},{width:100}];info.addRows([['TFC Investment Lab','Educational allocation tool · fictional CAD money'],['Starting amount CAD',data.budget/100],['Goal',data.goal],['Account for available cash',data.account],['Account explanation',accounts[data.account as Account].body],['Official account source',accounts[data.account as Account].url],['Assumptions','No trading or FX fees. Cash earns no interest. No scenarios, returns or personal taxes calculated. Generic bonds use illustrative CAD $100 practice units, not real bond quotes; Yahoo snapshots are dated and refreshed quotes may be delayed. Direct crypto is not qualified for TFSA/RRSP/FHSA. Account balance does not measure contribution room. Fund costs include only verified expense ratios; other fund fees are unknown, not zero.'],['Editing','Edit allocation amounts in Portfolio column D. Cash and allocation formulas recalculate in Excel. Do not exceed the starting amount.'],['USD to CAD exchange rate',fx.rate],['FX date',fx.date],['FX source',fx.source]]);
 const p=wb.addWorksheet('Portfolio');p.columns=[{width:32},{width:20},{width:18},{width:23},{width:20},{width:22},{width:20},{width:24},{width:22}];p.addRow(['Investment','Asset type','Identifier','Amount CAD (editable)','Portfolio allocation','Reference shares','Annual ETF MER','Known annual ETF cost CAD','Account (editable)']);assets.forEach((a,i)=>{const r=i+2,price=priceFor(a,data.market),cad=price?price.close*(price.currency==='USD'?fx.rate:1):0;p.addRow([a.name,a.group,a.id,data.amounts[i]/100,{formula:`IF('Portfolio settings'!B2=0,0,D${r}/'Portfolio settings'!B2)`,result:data.amounts[i]/data.budget},price?{formula:`IF('References'!F${r}=0,0,D${r}/'References'!F${r})`,result:data.amounts[i]/100/cad}:'Dollar allocation only',a.feeKnown===false?null:a.fee,{formula:`ROUND(D${r}*G${r},2)`,result:Math.round(data.amounts[i]*a.fee)/100},assigned[i]]);p.getCell(`I${r}`).dataValidation={type:'list',allowBlank:false,formulae:[`"${accountTypes.join(',')}"`],showErrorMessage:true,error:'Choose TFSA, RRSP, FHSA or Non-registered.'};p.getCell(`D${r}`).dataValidation={type:'decimal',operator:'between',formulae:[0,`'Portfolio settings'!$B$2-SUM($D$2:$D$${assets.length+1})+D${r}`],showErrorMessage:true,error:'Use a non-negative amount within the remaining budget.'}});
 const cashRow=assets.length+2,totalRow=cashRow+1;p.addRow(['Available cash','Cash','CAD',{formula:`'Portfolio settings'!B2-SUM(D2:D${cashRow-1})`,result:mix.cash/100},{formula:`D${cashRow}/'Portfolio settings'!B2`,result:mix.cash/data.budget},null,0,0,{formula:"'Portfolio settings'!B4",result:data.account}]);p.addRow(['TOTAL',null,null,{formula:`SUM(D2:D${cashRow})`,result:data.budget/100},{formula:`SUM(E2:E${cashRow})`,result:1},null,null,{formula:`SUM(H2:H${cashRow})`,result:mix.fee/100}]);p.getColumn(4).numFmt='"CAD "#,##0.00';p.getColumn(5).numFmt='0.0%';p.getColumn(6).numFmt='0.000000';p.getColumn(7).numFmt='0.00%';p.getColumn(8).numFmt='"CAD "#,##0.00';
 const dist=wb.addWorksheet('Asset distribution');dist.columns=[{width:22},{width:24},{width:20}];dist.addRow(['Asset type','Amount CAD','Allocation']);groups.forEach((g,i)=>{const v=mix.byGroup[i].value,r=i+2;dist.addRow([g,{formula:`SUMIF(Portfolio!B2:B${cashRow},A${r},Portfolio!D2:D${cashRow})`,result:v/100},{formula:`B${r}/'Portfolio settings'!B2`,result:v/data.budget}])});dist.getColumn(2).numFmt='"CAD "#,##0.00';dist.getColumn(3).numFmt='0.0%';
 const ac=wb.addWorksheet('Account distribution');ac.columns=[{width:23},{width:24},{width:20},...groups.map(()=>({width:24})),{width:95}];ac.addRow(['Account','Value CAD','Portfolio allocation',...groups.map(g=>g+' CAD'),'Eligibility & tax context']);byAccount.forEach((a,i)=>{const r=i+2;ac.addRow([a.account,{formula:`SUMIF(Portfolio!I2:I${cashRow},A${r},Portfolio!D2:D${cashRow})`,result:a.value/100},{formula:`B${r}/'Portfolio settings'!B2`,result:a.value/data.budget},...a.byGroup.map(g=>({formula:`SUMIFS(Portfolio!D2:D${cashRow},Portfolio!I2:I${cashRow},A${r},Portfolio!B2:B${cashRow},"${g.group}")`,result:g.value/100})),accounts[a.account].body]);});ac.getColumn(2).numFmt='"CAD "#,##0.00';ac.getColumn(3).numFmt='0.0%';[4,5,6,7,8].forEach(i=>ac.getColumn(i).numFmt='"CAD "#,##0.00');
 const refs=wb.addWorksheet('References');refs.columns=[{width:32},{width:16},{width:20},{width:18},{width:17},{width:22},{width:75},{width:95}];refs.addRow(['Asset','Identifier','Trading currency','Quote / reference price','Market timestamp / date','Reference price CAD','Source','Description & risk']);assets.forEach(a=>{const price=priceFor(a,data.market);refs.addRow([a.name,a.id,price?.currency??'Not quoted',price?.close??null,price?.date??null,price?price.close*(price.currency==='USD'?fx.rate:1):0,price?.source??'Educational dollar allocation; no unit price assumed',`${a.description} ${a.risk} ${price?.kind??'No unit quote'}. ${a.feeKnown===false?'Fund expense ratio not yet verified.':''}`])});
 wb.eachSheet(s=>{s.views=[{state:'frozen',ySplit:1}];s.eachRow((row,n)=>{row.height=n===1?34:55;row.alignment={wrapText:true,vertical:'middle'};if(n===1){row.font={bold:true,color:{argb:'FFFFFFFF'}};row.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF1A1A57'}}}else if(n%2===0)row.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFFBF6EE'}};});});info.getRow(7).height=80;return wb;
}
export async function downloadBuilder(data:BuilderState){const wb=await createBuilderWorkbook(data),buffer=await wb.xlsx.writeBuffer(),url=URL.createObjectURL(new Blob([new Uint8Array(buffer)],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));const a=document.createElement('a');a.href=url;a.download='TFC-Portfolio.xlsx';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
