import {catalogue,reference,accounts,type Account} from './lab';
import type {MarketData} from './market';
import snapshot from './price-snapshot.json';
export const groups=['Stocks','ETFs','Bonds','Cash','Crypto'] as const;
export type Group=typeof groups[number];
export const groupColors:Record<Group,string>={Stocks:'#f9735c',ETFs:'#1a1a57',Bonds:'#6ed9b3',Cash:'#d1d5db',Crypto:'#fcd34d'};
export type Asset={id:string,name:string,group:Group,description:string,exposure:string,risk:string,fee:number,referenceIndex?:number,symbol?:string,feeKnown?:boolean};
export const assets:Asset[]=[...catalogue.map((c,i)=>({id:c.ticker,name:c.name,group:(c.type==='Stock'?'Stocks':'ETFs') as Group,description:c.description,exposure:i===3||i===4?'Canada':i===6?'Global':'United States',risk:c.type==='Stock'?'One company can lose value even when the wider market rises.':'A basket spreads company risk, but market losses are still possible.',fee:c.fee,referenceIndex:i,symbol:i===3||i>=4?c.ticker+'.TO':c.ticker,feeKnown:true})),
{id:'GOV-SHORT',name:'Short-term government bonds',group:'Bonds',description:'Lend money to a government for a shorter period. Interest rates can still change the resale value.',exposure:'Canada',risk:'Interest-rate and issuer risk; no guaranteed resale price.',fee:0},
{id:'GOV-LONG',name:'Long-term government bonds',group:'Bonds',description:'Government borrowing over a longer period. Prices usually react more strongly to changing interest rates.',exposure:'Canada',risk:'Longer maturity can mean bigger price swings.',fee:0},
{id:'CORPORATE',name:'Corporate bonds',group:'Bonds',description:'Lend money to companies. They promise payments, but may struggle to repay.',exposure:'Canada',risk:'Company credit risk and interest-rate risk.',fee:0},
{id:'HIGH-YIELD',name:'High-yield bonds',group:'Bonds',description:'Loans to companies with weaker credit ratings. Higher promised interest comes with greater default risk.',exposure:'Global',risk:'Higher default risk; prices can fall sharply.',fee:0},
{symbol:'BTC-USD',id:'BTC',name:'Bitcoin',group:'Crypto',description:'A digital asset transferred on a blockchain. Its value depends on what other people are willing to pay.',exposure:'Digital assets',risk:'High volatility, custody risk and possible major losses.',fee:0},
{symbol:'ETH-USD',id:'ETH',name:'Ethereum',group:'Crypto',description:'A blockchain network used for apps and digital contracts. Ether is its native crypto asset.',exposure:'Digital assets',risk:'High volatility, technology and custody risk.',fee:0},
{symbol:'SOL-USD',id:'SOL',name:'Solana',group:'Crypto',description:'A blockchain network used for apps and transactions. SOL is its native crypto asset.',exposure:'Digital assets',risk:'High volatility, network and custody risk.',fee:0}];
const stocks=[
['MSFT','Microsoft','United States','Software, Xbox gaming and cloud services.'],['NVDA','NVIDIA','United States','Chips used for gaming, AI and data centres.'],['GOOGL','Alphabet','United States','Google search, YouTube and other technology businesses.'],['AMZN','Amazon','United States','Online shopping, streaming and cloud services.'],['META','Meta Platforms','United States','Instagram, Facebook and WhatsApp.'],['TSLA','Tesla','United States','Electric vehicles, batteries and energy products.'],['NFLX','Netflix','United States','Subscription streaming and entertainment.'],['DIS','Disney','United States','Films, streaming, sports media and theme parks.'],['SPOT','Spotify','United States','Music, podcasts and audio subscriptions.'],['EA','Electronic Arts','United States','Video games and gaming services.'],['TTWO','Take-Two Interactive','United States','Game studios including Rockstar and 2K.'],['SBUX','Starbucks','United States','Coffee shops and packaged drinks.'],['MCD','McDonald’s','United States','Restaurants and a global franchise business.'],['COST','Costco','United States','Membership warehouses and retail shopping.'],['WMT','Walmart','United States','Retail stores and online shopping.'],['KO','Coca-Cola','United States','Soft drinks and other beverage brands.'],['PEP','PepsiCo','United States','Snacks, soft drinks and food brands.'],['V','Visa','United States','A network that processes digital payments.'],['MA','Mastercard','United States','A network connecting banks, merchants and card payments.'],['PYPL','PayPal','United States','Digital payments and online checkout.'],['LULU','lululemon','United States','Athletic clothing and accessories.'],['RY.TO','Royal Bank of Canada','Canada','Banking, insurance and financial services.'],['TD.TO','TD Bank','Canada','Personal and business banking.'],['BNS.TO','Scotiabank','Canada','Banking in Canada and international markets.'],['BMO.TO','Bank of Montreal','Canada','Banking and financial services.'],['ENB.TO','Enbridge','Canada','Energy transportation and utilities.'],['CNR.TO','Canadian National Railway','Canada','Rail freight across North America.'],['CP.TO','Canadian Pacific Kansas City','Canada','Rail freight connecting Canada, the U.S. and Mexico.'],['ATD.TO','Alimentation Couche-Tard','Canada','Convenience stores and fuel retail.'],['DOL.TO','Dollarama','Canada','Discount retail stores.'],['L.TO','Loblaw','Canada','Grocery, pharmacy and retail services.'],['CTC-A.TO','Canadian Tire','Canada','Retail stores, sports and automotive products.'],['BCE.TO','BCE','Canada','Telecommunications and media.'],['T.TO','Telus','Canada','Telecommunications and digital services.'],['OTEX.TO','OpenText','Canada','Software for business information management.'],['WCN.TO','Waste Connections','Canada','Waste collection, recycling and disposal services.']];
const funds=[['VTI','Vanguard Total U.S. Stock Market ETF','United States'],['VOO','Vanguard S&P 500 ETF','United States'],['QQQ','Invesco QQQ ETF','United States'],['VEA','Vanguard Developed Markets ETF','International'],['VWO','Vanguard Emerging Markets ETF','Emerging markets'],['VT','Vanguard Total World Stock ETF','Global'],['XIU.TO','iShares S&P/TSX 60 ETF','Canada'],['VCN.TO','Vanguard FTSE Canada All Cap ETF','Canada'],['ZCN.TO','BMO S&P/TSX Capped Composite ETF','Canada'],['XUU.TO','iShares U.S. Total Market ETF','United States'],['VUN.TO','Vanguard U.S. Total Market ETF','United States'],['XEF.TO','iShares Developed Markets ETF','International'],['VIU.TO','Vanguard Developed All Cap ex North America ETF','International'],['XEC.TO','iShares Emerging Markets ETF','Emerging markets'],['VEE.TO','Vanguard Emerging Markets All Cap ETF','Emerging markets']];
const bondFunds=[['XBB.TO','iShares Canadian Universe Bond ETF','Canada'],['VAB.TO','Vanguard Canadian Aggregate Bond ETF','Canada'],['ZAG.TO','BMO Aggregate Bond ETF','Canada'],['XSB.TO','iShares Canadian Short Term Bond ETF','Canada'],['VSB.TO','Vanguard Canadian Short Term Bond ETF','Canada'],['BND','Vanguard Total Bond Market ETF','United States'],['AGG','iShares Core U.S. Aggregate Bond ETF','United States'],['TLT','iShares 20+ Year Treasury Bond ETF','United States'],['HYG','iShares High Yield Corporate Bond ETF','United States']];
for(const [symbol,name,exposure,description] of stocks)assets.push({id:symbol,symbol,name,exposure,description,group:'Stocks',risk:'One company can experience large losses. Popularity does not guarantee investment success.',fee:0,feeKnown:true});
for(const [symbol,name,exposure] of funds)assets.push({id:symbol,symbol,name,exposure,description:'A stock ETF: a basket of companies. Check its holdings to understand market coverage and overlap.',group:'ETFs',risk:'Stock markets, currency and concentration can affect value. Returns are not guaranteed.',fee:0,feeKnown:false});
for(const [symbol,name,exposure] of bondFunds)assets.push({id:symbol,symbol,name,exposure,description:'A bond ETF: a basket of loans to governments or companies. Its price can change before you sell.',group:'Bonds',risk:'Interest-rate and credit risks. Bond funds do not promise a fixed repayment to you.',fee:0,feeKnown:false});
for(const [symbol,name] of [['ADA-USD','Cardano'],['AVAX-USD','Avalanche'],['LINK-USD','Chainlink'],['DOGE-USD','Dogecoin'],['XRP-USD','XRP']])assets.push({id:symbol,symbol,name,exposure:'Digital assets',description:'A digital crypto asset. Its value can change quickly with demand, technology and market sentiment.',group:'Crypto',risk:'High volatility, custody and technology risks; major losses are possible.',fee:0,feeKnown:true});
export const snapshotFX={rate:snapshot.quotes['CAD=X'].price,date:snapshot.quotes['CAD=X'].asOf,source:snapshot.quotes['CAD=X'].source};
export const accountTypes=['TFSA','RRSP','FHSA','Non-registered'] as Account[];
export function accountDistribution(budget:number,amounts:number[],assigned:Account[],cashAccount:Account){const mix=allocation(budget,amounts);if(assigned.length!==assets.length||assigned.some(a=>!accountTypes.includes(a))||!accountTypes.includes(cashAccount))throw new Error('Choose a valid account for each holding.');return accountTypes.map(account=>{const values=amounts.map((v,i)=>assigned[i]===account?v:0),cash=account===cashAccount?mix.cash:0;return {account,value:values.reduce((a,b)=>a+b,0)+cash,cash,holdings:values.filter(Boolean).length,byGroup:groups.map(group=>({group,value:group==='Cash'?cash:values.reduce((s,v,i)=>s+(assets[i].group===group?v:0),0)})),crypto:values.reduce((s,v,i)=>s+(assets[i].group==='Crypto'?v:0),0)}})}
export function priceFor(a:Asset,market?:MarketData|null){const q=a.symbol?(market?.quotes[a.symbol]??(snapshot.quotes as Record<string,{currency:'CAD'|'USD',price:number,asOf:string,source:string}>)[a.symbol]):null;if(q)return {ticker:a.id,currency:q.currency,close:q.price,date:q.asOf,source:q.source,kind:market?.quotes[a.symbol??'']?'Yahoo quote (may be delayed)':'Dated Yahoo price snapshot'};const ref=referenceFor(a);return ref?{...ref,kind:'Dated reference close'}:{ticker:a.id,currency:'CAD' as const,close:100,date:'2026-10-02',source:'Illustrative practice unit — not a market quote',kind:'Illustrative practice price'};}
export type BuilderState={budget:number,amounts:number[],account:string,goal:string,assigned?:Account[],market?:MarketData|null};
export function allocation(budget:number,amounts:number[]){if(!Number.isSafeInteger(budget)||budget<=0||budget>100000000000||amounts.length!==assets.length||amounts.some(v=>!Number.isSafeInteger(v)||v<0))throw new Error('Use valid amounts in cents.');const invested=amounts.reduce((a,b)=>a+b,0);if(invested>budget)throw new Error('Your allocations exceed your budget.');const cash=budget-invested;const byGroup=groups.map(group=>({group,value:group==='Cash'?cash:amounts.reduce((s,v,i)=>s+(assets[i].group===group?v:0),0)}));return {invested,cash,byGroup,fee:amounts.reduce((s,v,i)=>s+Math.round(v*assets[i].fee),0)};}
export function allocate(budget:number,amounts:number[],index:number,value:number){if(!Number.isInteger(index)||index<0||index>=assets.length)throw new Error('Choose an asset.');const next=[...amounts];next[index]=value;allocation(budget,next);return next;}
export function referenceFor(a:Asset){return a.referenceIndex===undefined?null:reference.prices[a.referenceIndex];}
// Educational labels, not issuer classifications or investment recommendations.
export function industryFor(a:Asset):string{
 if(a.group==='Crypto')return 'Digital assets';
 if(a.group==='Bonds')return 'Fixed income';
 if(a.group==='ETFs')return ['QQQ'].includes(a.id)?'Technology basket':'Broad market';
 const id=a.id.replace('.TO','');
 if(['AAPL','MSFT','NVDA','GOOGL','META','SHOP','OTEX'].includes(id))return 'Technology';
 if(['RBLX','EA','TTWO'].includes(id))return 'Gaming';
 if(['NFLX','DIS','SPOT'].includes(id))return 'Entertainment';
 if(['AMZN','COST','WMT','ATD','DOL','L','CTC-A'].includes(id))return 'Retail';
 if(['NKE','LULU'].includes(id))return 'Apparel & sports';
 if(['SBUX','MCD','KO','PEP'].includes(id))return 'Food & drinks';
 if(['V','MA','PYPL','RY','TD','BNS','BMO'].includes(id))return 'Financial services';
 if(['BCE','T'].includes(id))return 'Telecommunications';
 if(id==='ENB')return 'Energy';
 if(['CNR','CP','WCN'].includes(id))return 'Industrials';
 if(id==='TSLA')return 'Automotive';
 return 'Other';
}
