import ExcelJS from 'exceljs';
import {catalogue,accounts,cadPrices,holdingValues,total,annualFee,simulate,scenarios,validatePortfolio,type Snapshot,type Portfolio,type Event} from './lab';
export type ExportData={original:Snapshot,revised:Portfolio,event:Event|null,reflection:string};
export async function createWorkbook(data:ExportData){
 const {original,revised,event}=data,prices=cadPrices(original.prices),rates=event?.rates??catalogue.map(()=>0),result=simulate(original.portfolio,prices,rates),before=holdingValues(original.portfolio,prices),after=holdingValues(revised,result.prices);
 validatePortfolio(revised);if(total(revised,result.prices)!==result.total)throw new Error('Revised holdings and cash must equal the post-event value.');
 const wb=new ExcelJS.Workbook();wb.creator='Teen Finance Club';wb.created=new Date();wb.calcProperties.fullCalcOnLoad=true;
 const workshop=wb.addWorksheet('Workshop');workshop.columns=[{width:32},{width:104}];workshop.addRows([
 ['TFC Investment Lab','Fictional money. Real price references. Fictional outcomes. CAD.'],['Goal',original.goal],['When money is needed',original.horizon],['Comfort with risk',original.risk],['Practice account',original.account],['Starting budget CAD',original.budget/100],['Account explanation',accounts[original.account].body],['Official CRA source',accounts[original.account].url],['Account rules checked','2026-10-02'],['Event',event?scenarios.find(s=>s.id===event.id)!.name:'No event applied'],['Company in spotlight',event&&(event.id==='company'||event.id==='mixed')?catalogue[event.target].name:'Not applicable'],['Event assumptions',event?scenarios.find(s=>s.id===event.id)!.description:'Prices unchanged'],['Original value CAD',original.budget/100],['After event CAD',result.total/100],['Event gain / loss CAD',result.change/100],['Revised value CAD',total(revised,result.prices)/100],['Trading fees CAD',0],['Calculation rules','Fractional shares allowed for learning. Every holding value is rounded to cents. Cash is counted once and earns no interest. FX stays fixed. Event changes are fictional; no dividends, taxes, inflation or elapsed time. Account choice never changes market return. ETF cost estimates are annual illustrations, not deducted again from event prices.'],['What did you change, and why?',data.reflection],['Price provenance',original.prices.verified?'Built-in dated closing snapshot checked against linked sources.':'Imported snapshot: sources supplied by the user; app validates structure, not authenticity.'],['Editing workbook','Shares and scenario rates are editable. Formulas recalculate values, allocations and cash. Keep purchases within cash and do not make cash negative. This workbook is independent of the in-memory app.'],['Privacy','No login or database. Download before leaving.'],
 ]);
 workshop.getCell('B13').value={formula:"'Original portfolio'!E10",result:original.budget/100};workshop.getCell('B14').value={formula:"'Scenario results'!G10",result:result.total/100};workshop.getCell('B15').value={formula:"'Scenario results'!H10",result:result.change/100};workshop.getCell('B16').value={formula:"'Revised portfolio'!E10",result:total(revised,result.prices)/100};
 const refs=wb.addWorksheet('Reference prices');refs.columns=[{width:14},{width:14},{width:20},{width:22},{width:17},{width:66},{width:16},{width:66},{width:3},{width:3},{width:22},{width:66}];refs.addRow(['Ticker','Trading currency','Real closing price','Reference price CAD','Close date','Price source','Annual ETF MER','MER / issuer source']);
 refs.getCell('K1').value='USD to CAD rate';refs.getCell('L1').value=original.prices.fx.rate;refs.getCell('K2').value='FX date';refs.getCell('L2').value=original.prices.fx.date;refs.getCell('K3').value='FX source';refs.getCell('L3').value=original.prices.fx.source;
 original.prices.prices.forEach((p,i)=>{const r=i+2;refs.getCell(`A${r}`).value=p.ticker;refs.getCell(`B${r}`).value=p.currency;refs.getCell(`C${r}`).value=p.close;refs.getCell(`D${r}`).value={formula:`C${r}*IF(B${r}="USD",$L$1,1)`,result:prices[i]};refs.getCell(`E${r}`).value=p.date;refs.getCell(`F${r}`).value=p.source;refs.getCell(`G${r}`).value=catalogue[i].fee;refs.getCell(`H${r}`).value=catalogue[i].type==='ETF'?catalogue[i].info:'No fund MER for this individual stock';});refs.getColumn(3).numFmt='0.00';refs.getColumn(4).numFmt='"CAD "0.000000';refs.getColumn(7).numFmt='0.00%';refs.getCell('L1').numFmt='0.0000';
 function makePortfolio(name:string,p:Portfolio,market:number[],isRevised:boolean){const s=wb.addWorksheet(name);s.columns=[{width:30},{width:14},{width:22},{width:24},{width:24},{width:18},{width:18},{width:22}];s.addRow(['Holding','Ticker','Shares (editable)','Price CAD per share','Holding value CAD','Allocation','Annual ETF MER','Annual cost estimate CAD']);const vals=holdingValues(p,market),amount=total(p,market);catalogue.forEach((c,i)=>{const r=i+2;s.addRow([c.name,c.ticker,p.shares[i],{formula:isRevised?`'Scenario results'!E${r}`:`'Reference prices'!D${r}`,result:market[i]},{formula:`ROUND(C${r}*D${r},2)`,result:vals[i]/100},{formula:`IF($E$10=0,0,E${r}/$E$10)`,result:amount?vals[i]/amount:0},{formula:`'Reference prices'!G${r}`,result:c.fee},{formula:`ROUND(E${r}*G${r},2)`,result:Math.round(vals[i]*c.fee)/100}]);});s.addRow(['Cash','CAD',null,null,{formula:isRevised?"'Scenario results'!G10-SUM(E2:E8)":'Workshop!B6-SUM(E2:E8)',result:p.cash/100},{formula:'IF(E10=0,0,E9/E10)',result:amount?p.cash/amount:0},0,0]);s.addRow(['TOTAL',null,null,null,{formula:'SUM(E2:E9)',result:amount/100},{formula:'IF(E10=0,0,SUM(F2:F9))',result:amount?1:0},null,{formula:'SUM(H2:H9)',result:annualFee(p,market)/100}]);s.getColumn(3).numFmt='0.000000';s.getColumn(4).numFmt='"CAD "0.000000';s.getColumn(5).numFmt='"CAD "#,##0.00';s.getColumn(6).numFmt='0.0%';s.getColumn(7).numFmt='0.00%';s.getColumn(8).numFmt='"CAD "#,##0.00';for(let r=2;r<=8;r++)s.getCell(`C${r}`).dataValidation={type:'decimal',operator:'greaterThanOrEqual',formulae:[0],showErrorMessage:true,errorTitle:'Non-negative shares',error:'Use zero or a positive share quantity.'};return s;}
 makePortfolio('Original portfolio',original.portfolio,prices,false);
 const sc=wb.addWorksheet('Scenario results');sc.columns=[{width:14},{width:22},{width:22},{width:24},{width:24},{width:22},{width:22},{width:22}];sc.addRow(['Holding','Original shares','Fictional change (editable)','Real reference CAD','Fictional event CAD','Original value CAD','After event CAD','Gain / loss CAD']);catalogue.forEach((c,i)=>{const r=i+2;sc.addRow([c.ticker,{formula:`'Original portfolio'!C${r}`,result:original.portfolio.shares[i]},rates[i],{formula:`'Reference prices'!D${r}`,result:prices[i]},{formula:`D${r}*(1+C${r})`,result:result.prices[i]},{formula:`'Original portfolio'!E${r}`,result:before[i]/100},{formula:`ROUND(B${r}*E${r},2)`,result:result.values[i]/100},{formula:`G${r}-F${r}`,result:result.changes[i]/100}]);});sc.addRow(['Cash',null,0,null,null,{formula:"'Original portfolio'!E9",result:original.portfolio.cash/100},{formula:'F9',result:original.portfolio.cash/100},0]);sc.addRow(['TOTAL',null,null,null,null,{formula:'SUM(F2:F9)',result:original.budget/100},{formula:'SUM(G2:G9)',result:result.total/100},{formula:'G10-F10',result:result.change/100}]);sc.getColumn(2).numFmt='0.000000';sc.getColumn(3).numFmt='+0.0%;[Red]−0.0%;0.0%';[4,5].forEach(i=>sc.getColumn(i).numFmt='"CAD "0.000000');[6,7].forEach(i=>sc.getColumn(i).numFmt='"CAD "#,##0.00');sc.getColumn(8).numFmt='[Green]+"CAD "#,##0.00;[Red]−"CAD "#,##0.00;"CAD "0.00';for(let r=2;r<=8;r++)sc.getCell(`C${r}`).dataValidation={type:'decimal',operator:'greaterThan',formulae:[-1],showErrorMessage:true,error:'Use a change greater than −100%.'};
 makePortfolio('Revised portfolio',revised,result.prices,true);
 const compare=wb.addWorksheet('Comparison');compare.columns=[{width:24},{width:22},{width:22},{width:22},{width:22},{width:22},{width:22}];compare.addRow(['Holding','Original CAD','After event CAD','Revised CAD','Original shares','Revised shares','Revised allocation']);catalogue.forEach((c,i)=>{const r=i+2;compare.addRow([c.ticker,{formula:`'Original portfolio'!E${r}`,result:before[i]/100},{formula:`'Scenario results'!G${r}`,result:result.values[i]/100},{formula:`'Revised portfolio'!E${r}`,result:after[i]/100},{formula:`'Original portfolio'!C${r}`,result:original.portfolio.shares[i]},{formula:`'Revised portfolio'!C${r}`,result:revised.shares[i]},{formula:`'Revised portfolio'!F${r}`,result:result.total?after[i]/result.total:0}]);});compare.addRow(['Cash',{formula:"'Original portfolio'!E9",result:original.portfolio.cash/100},{formula:"'Scenario results'!G9",result:original.portfolio.cash/100},{formula:"'Revised portfolio'!E9",result:revised.cash/100},null,null,{formula:"'Revised portfolio'!F9",result:result.total?revised.cash/result.total:0}]);compare.addRow(['TOTAL',{formula:'SUM(B2:B9)',result:original.budget/100},{formula:'SUM(C2:C9)',result:result.total/100},{formula:'SUM(D2:D9)',result:result.total/100},null,null,{formula:'SUM(G2:G9)',result:result.total?1:0}]);[2,3,4].forEach(i=>compare.getColumn(i).numFmt='"CAD "#,##0.00');[5,6].forEach(i=>compare.getColumn(i).numFmt='0.000000');compare.getColumn(7).numFmt='0.0%';
 wb.eachSheet(s=>{s.views=[{state:'frozen',ySplit:1}];s.eachRow((row,n)=>{row.alignment={vertical:'top',wrapText:true};row.height=n===1?36:44;if(n===1){row.font={bold:true,color:{argb:'FFFFFFFF'}};row.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF1A1A57'}}}else{row.font={color:{argb:'FF1A1A57'},size:11};if(n%2===0)row.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFFBF6EE'}}}})});workshop.getRow(7).height=100;workshop.getRow(18).height=95;workshop.getRow(19).height=120;workshop.getRow(21).height=80;refs.getRow(3).height=80;
 return wb;
}
export async function downloadWorkbook(data:ExportData){const wb=await createWorkbook(data);const buffer=await wb.xlsx.writeBuffer();const blob=new Blob([new Uint8Array(buffer)],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='TFC-Investment-Lab.xlsx';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
